# 第十五章 异常

## 异常体系

![image-20210708140209249](http://note.youdao.com/yws/public/resource/7d81e6a39024a96dd86efacf29f4ca80/xmlnote/WEBRESOURCE91502447ec184addb61a72d6cbcb652b/605)

从继承关系可知：`Throwable`是异常体系的根，它继承自`Object`。`Throwable`有两个体系：`Error`和`Exception`，`Error`表示严重的错误，程序对此一般无能为力，例如：

- `OutOfMemoryError`：内存耗尽
- `NoClassDefFoundError`：无法加载某个Class
- `StackOverflowError`：栈溢出

而`Exception`则是运行时的错误，它可以被捕获并处理。

某些异常是应用程序逻辑处理的一部分，应该捕获并处理。例如：

- `NumberFormatException`：数值类型的格式错误
- `FileNotFoundException`：未找到文件
- `SocketException`：读取网络失败





## 语法

在Java中，凡是可能抛出异常的语句，都可以用`try ... catch`捕获。

可以使用多个`catch`语句，每个`catch`分别捕获对应的`Exception`及其子类。

> 注意，小的在前（优先），大的在后，要不被大的一手遮天，小的永不见天日



## 执行顺序

try==>catch==>finally

注意，如果try或者catch中有return，**则只把return语句放在finally之后执行，其他顺序保持不变。**

 在`catch`中抛出异常，不会影响`finally`的执行。JVM会先执行`finally`，然后抛出异常。



